### PR TITLE
Set style fix

### LINKED ISSUE #70: Fix setStyle so that id is no longer an argument

### PR DESCRIPTION
**Pull request by lkriffell**
### This PRs additions:
Adds passing happy path testing for the updated setStyle (setStyle no longer requires user id as an argument)
Edits utils.js to hold context of a mocked current user's id `{ context: { auth: { user: { id: 1 } } } } }`
 
### Relevant tickets: 
closes #70

### CODE REVIEW

File: code/api/src/modules/tests/utils.js [hunk 1]
```diff
@@ -5,7 +5,13 @@ import schema from '../../setup/schema';
...
 server.use("/", graphqlHTTP({
     schema: schema,
-    graphiql: false
+    graphiql: false,
+    context: {
+      auth: {
+        user: { id: 1 },
+        isAuthenticated: true
+      }
+    }
```
Comment (hashmaster3k) [inline code/api/src/modules/tests/utils.js:14]: Nice! Thanks for figuring this out!
